apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: aimvector/python:metrics
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-app
spec:
  type: ClusterIP
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: example-app
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      app: example-app

---
# commands:
# - k port-forward svc/prometheus-operated 9090:9090 -n monitoring
# - k port-forward svc/example-service 5000:80 -n default
# curl -g 'http://localhost:9090/api/v1/query_range?query=rate(python_request_operations_total[1m])&start=2024-03-23T10:42:56.00Z&end=2024-03-23T10:51:28.00Z&step=15s'
