apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: external-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: example-deploy
  pollingInterval: 15
  cooldownPeriod: 15
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
  triggers:
    - type: external
      metadata:
        scalerAddress: external-scaler-service.default.svc.cluster.local:50051
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        threshold: 11
        query: sum(rate(python_request_operations_total[1m]))
        metricName: rps # requests per second
