apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-scaler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-scaler
  template:
    metadata:
      labels:
        app: external-scaler
    spec:
      containers:
        - name: external-scaler-container
          image: skandarchahbouni/external-scaler:v2.0
          ports:
            - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: external-scaler-service
spec:
  selector:
    app: external-scaler
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
