apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: so-1
  namespace: default
spec:
  scaleTargetRef:
    name: app-1
  pollingInterval: 30
  cooldownPeriod: 15
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        threshold: "5"
        query: sum(rate(python_request_operations_total{service="app-1"}[1m]))
