# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import externalscaler_pb2 as externalscaler__pb2


class ExternalScalerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsActive = channel.unary_unary(
                '/externalscaler.ExternalScaler/IsActive',
                request_serializer=externalscaler__pb2.ScaledObjectRef.SerializeToString,
                response_deserializer=externalscaler__pb2.IsActiveResponse.FromString,
                )
        self.StreamIsActive = channel.unary_stream(
                '/externalscaler.ExternalScaler/StreamIsActive',
                request_serializer=externalscaler__pb2.ScaledObjectRef.SerializeToString,
                response_deserializer=externalscaler__pb2.IsActiveResponse.FromString,
                )
        self.GetMetricSpec = channel.unary_unary(
                '/externalscaler.ExternalScaler/GetMetricSpec',
                request_serializer=externalscaler__pb2.ScaledObjectRef.SerializeToString,
                response_deserializer=externalscaler__pb2.GetMetricSpecResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/externalscaler.ExternalScaler/GetMetrics',
                request_serializer=externalscaler__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=externalscaler__pb2.GetMetricsResponse.FromString,
                )


class ExternalScalerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIsActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetricSpec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalScalerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsActive': grpc.unary_unary_rpc_method_handler(
                    servicer.IsActive,
                    request_deserializer=externalscaler__pb2.ScaledObjectRef.FromString,
                    response_serializer=externalscaler__pb2.IsActiveResponse.SerializeToString,
            ),
            'StreamIsActive': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamIsActive,
                    request_deserializer=externalscaler__pb2.ScaledObjectRef.FromString,
                    response_serializer=externalscaler__pb2.IsActiveResponse.SerializeToString,
            ),
            'GetMetricSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetricSpec,
                    request_deserializer=externalscaler__pb2.ScaledObjectRef.FromString,
                    response_serializer=externalscaler__pb2.GetMetricSpecResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=externalscaler__pb2.GetMetricsRequest.FromString,
                    response_serializer=externalscaler__pb2.GetMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'externalscaler.ExternalScaler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExternalScaler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/externalscaler.ExternalScaler/IsActive',
            externalscaler__pb2.ScaledObjectRef.SerializeToString,
            externalscaler__pb2.IsActiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamIsActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/externalscaler.ExternalScaler/StreamIsActive',
            externalscaler__pb2.ScaledObjectRef.SerializeToString,
            externalscaler__pb2.IsActiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetricSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/externalscaler.ExternalScaler/GetMetricSpec',
            externalscaler__pb2.ScaledObjectRef.SerializeToString,
            externalscaler__pb2.GetMetricSpecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/externalscaler.ExternalScaler/GetMetrics',
            externalscaler__pb2.GetMetricsRequest.SerializeToString,
            externalscaler__pb2.GetMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
