# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: externalscaler.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xternalscaler.proto\x12\x0e\x65xternalscaler\"\xb6\x01\n\x0fScaledObjectRef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12K\n\x0escalerMetadata\x18\x03 \x03(\x0b\x32\x33.externalscaler.ScaledObjectRef.ScalerMetadataEntry\x1a\x35\n\x13ScalerMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x10IsActiveResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"H\n\x15GetMetricSpecResponse\x12/\n\x0bmetricSpecs\x18\x01 \x03(\x0b\x32\x1a.externalscaler.MetricSpec\"4\n\nMetricSpec\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x12\n\ntargetSize\x18\x02 \x01(\x03\"a\n\x11GetMetricsRequest\x12\x38\n\x0fscaledObjectRef\x18\x01 \x01(\x0b\x32\x1f.externalscaler.ScaledObjectRef\x12\x12\n\nmetricName\x18\x02 \x01(\t\"G\n\x12GetMetricsResponse\x12\x31\n\x0cmetricValues\x18\x01 \x03(\x0b\x32\x1b.externalscaler.MetricValue\"6\n\x0bMetricValue\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x13\n\x0bmetricValue\x18\x02 \x01(\x03\x32\xec\x02\n\x0e\x45xternalScaler\x12O\n\x08IsActive\x12\x1f.externalscaler.ScaledObjectRef\x1a .externalscaler.IsActiveResponse\"\x00\x12W\n\x0eStreamIsActive\x12\x1f.externalscaler.ScaledObjectRef\x1a .externalscaler.IsActiveResponse\"\x00\x30\x01\x12Y\n\rGetMetricSpec\x12\x1f.externalscaler.ScaledObjectRef\x1a%.externalscaler.GetMetricSpecResponse\"\x00\x12U\n\nGetMetrics\x12!.externalscaler.GetMetricsRequest\x1a\".externalscaler.GetMetricsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'externalscaler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._options = None
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_SCALEDOBJECTREF']._serialized_start=41
  _globals['_SCALEDOBJECTREF']._serialized_end=223
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._serialized_start=170
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._serialized_end=223
  _globals['_ISACTIVERESPONSE']._serialized_start=225
  _globals['_ISACTIVERESPONSE']._serialized_end=259
  _globals['_GETMETRICSPECRESPONSE']._serialized_start=261
  _globals['_GETMETRICSPECRESPONSE']._serialized_end=333
  _globals['_METRICSPEC']._serialized_start=335
  _globals['_METRICSPEC']._serialized_end=387
  _globals['_GETMETRICSREQUEST']._serialized_start=389
  _globals['_GETMETRICSREQUEST']._serialized_end=486
  _globals['_GETMETRICSRESPONSE']._serialized_start=488
  _globals['_GETMETRICSRESPONSE']._serialized_end=559
  _globals['_METRICVALUE']._serialized_start=561
  _globals['_METRICVALUE']._serialized_end=615
  _globals['_EXTERNALSCALER']._serialized_start=618
  _globals['_EXTERNALSCALER']._serialized_end=982
# @@protoc_insertion_point(module_scope)
